[tool.poetry]
name = "vinor"
version = "0.1.0"
description = ""
authors = ["VinorTeam <opensource@vinor.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
